using System.Text.RegularExpressions;

namespace QubicExplorer.Shared.Constants;

/// <summary>
/// Special virtual transaction prefixes for smart contract lifecycle events.
/// These are not real transactions but are used as txHash for logs generated by these events.
/// Format: {PREFIX}_{TICK_NUMBER} (e.g., SC_END_TICK_TX_42087259)
/// </summary>
public static class SpecialTransactionTypes
{
    public const string ScInitialize = "SC_INITIALIZE_TX";
    public const string ScBeginEpoch = "SC_BEGIN_EPOCH_TX";
    public const string ScBeginTick = "SC_BEGIN_TICK_TX";
    public const string ScEndTick = "SC_END_TICK_TX";
    public const string ScEndEpoch = "SC_END_EPOCH_TX";

    private static readonly string[] AllPrefixes =
    {
        ScInitialize,
        ScBeginEpoch,
        ScBeginTick,
        ScEndTick,
        ScEndEpoch
    };

    private static readonly Regex SpecialTxPattern = new(
        @"^(SC_INITIALIZE_TX|SC_BEGIN_EPOCH_TX|SC_BEGIN_TICK_TX|SC_END_TICK_TX|SC_END_EPOCH_TX)_(\d+)$",
        RegexOptions.Compiled);

    /// <summary>
    /// Check if the txHash is a special virtual transaction
    /// </summary>
    public static bool IsSpecialTransaction(string? txHash)
    {
        if (string.IsNullOrEmpty(txHash)) return false;
        return SpecialTxPattern.IsMatch(txHash);
    }

    /// <summary>
    /// Parse a special transaction hash into its components
    /// </summary>
    public static (string Type, ulong TickNumber)? ParseSpecialTransaction(string? txHash)
    {
        if (string.IsNullOrEmpty(txHash)) return null;

        var match = SpecialTxPattern.Match(txHash);
        if (!match.Success) return null;

        return (match.Groups[1].Value, ulong.Parse(match.Groups[2].Value));
    }

    /// <summary>
    /// Get a human-readable name for the special transaction type
    /// </summary>
    public static string GetTypeName(string type) => type switch
    {
        ScInitialize => "Smart Contract Initialize",
        ScBeginEpoch => "Smart Contract Begin Epoch",
        ScBeginTick => "Smart Contract Begin Tick",
        ScEndTick => "Smart Contract End Tick",
        ScEndEpoch => "Smart Contract End Epoch",
        _ => type
    };
}

public static class LogTypes
{
    public const byte QuTransfer = 0;
    public const byte AssetIssuance = 1;
    public const byte AssetOwnershipChange = 2;
    public const byte AssetPossessionChange = 3;
    public const byte ContractErrorMessage = 4;
    public const byte ContractWarningMessage = 5;
    public const byte ContractInformationMessage = 6;
    public const byte ContractDebugMessage = 7;
    public const byte Burning = 8;
    public const byte DustBurning = 9;
    public const byte SpectrumStats = 10;
    public const byte AssetOwnershipManagingContractChange = 11;
    public const byte AssetPossessionManagingContractChange = 12;
    public const byte ContractReserveDeduction = 13;
    public const byte OracleQueryStatusChange = 14;
    public const byte CustomMessage = 255;

    // CustomMessage operation codes
    public const ulong CustomMessageOpStartDistributeRewards = 6217575821008262227; // STA_DDIV
    public const ulong CustomMessageOpEndDistributeRewards = 6217575821008457285;   // END_DDIV
    public const ulong CustomMessageOpStartEpoch = 4850183582582395987;             // STA_EPOC
    public const ulong CustomMessageOpEndEpoch = 4850183582582591045;               // END_EPOC

    // Number of computors (for reward per share calculation)
    public const int NumberOfComputors = 676;

    public static string GetName(byte logType) => logType switch
    {
        QuTransfer => "QU_TRANSFER",
        AssetIssuance => "ASSET_ISSUANCE",
        AssetOwnershipChange => "ASSET_OWNERSHIP_CHANGE",
        AssetPossessionChange => "ASSET_POSSESSION_CHANGE",
        ContractErrorMessage => "CONTRACT_ERROR_MESSAGE",
        ContractWarningMessage => "CONTRACT_WARNING_MESSAGE",
        ContractInformationMessage => "CONTRACT_INFORMATION_MESSAGE",
        ContractDebugMessage => "CONTRACT_DEBUG_MESSAGE",
        Burning => "BURNING",
        DustBurning => "DUST_BURNING",
        SpectrumStats => "SPECTRUM_STATS",
        AssetOwnershipManagingContractChange => "ASSET_OWNERSHIP_MANAGING_CONTRACT_CHANGE",
        AssetPossessionManagingContractChange => "ASSET_POSSESSION_MANAGING_CONTRACT_CHANGE",
        ContractReserveDeduction => "CONTRACT_RESERVE_DEDUCTION",
        OracleQueryStatusChange => "ORACLE_QUERY_STATUS_CHANGE",
        CustomMessage => "CUSTOM_MESSAGE",
        _ => $"UNKNOWN_{logType}"
    };

    public static bool IsTransferType(byte logType) => logType switch
    {
        QuTransfer or AssetOwnershipChange or AssetPossessionChange => true,
        _ => false
    };

    public static bool IsContractLog(byte logType) => logType switch
    {
        ContractErrorMessage or ContractWarningMessage or ContractInformationMessage or ContractDebugMessage => true,
        _ => false
    };
}
