namespace QubicExplorer.Shared.DTOs;

public record TransactionDto(
    string Hash,
    ulong TickNumber,
    uint Epoch,
    string FromAddress,
    string ToAddress,
    ulong Amount,
    ushort InputType,
    bool Executed,
    DateTime Timestamp
);

public record TransactionDetailDto(
    string Hash,
    ulong TickNumber,
    uint Epoch,
    string FromAddress,
    string ToAddress,
    ulong Amount,
    ushort InputType,
    string? InputData,
    bool Executed,
    DateTime Timestamp,
    List<LogDto> Logs
);

/// <summary>
/// DTO for special virtual transactions (smart contract lifecycle events)
/// These are not real transactions but virtual ones generated by the protocol.
/// </summary>
public record SpecialTransactionDto(
    string TxHash,
    string SpecialType,
    string SpecialTypeName,
    ulong TickNumber,
    DateTime Timestamp,
    List<LogDto> Logs
);
